//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVPHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienBanVPHC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienBanVPHC()
        {
            this.CTBienBanVPHCs = new HashSet<CTBienBanVPHC>();
            this.QuyetDinhTTTVs = new HashSet<QuyetDinhTTTV>();
            this.QuyetDinhXPVPHCs = new HashSet<QuyetDinhXPVPHC>();
        }
    
        public string SoBBVPHC { get; set; }
        public string SoQuyen { get; set; }
        public string VeViecLapBB { get; set; }
        public string CanCuLapBB { get; set; }
        public string GioLapBB { get; set; }
        public string PhutLapBB { get; set; }
        public Nullable<System.DateTime> NgayLapBB { get; set; }
        public string DiaDiemLapBB { get; set; }
        public string MaNV1 { get; set; }
        public string MaNV2 { get; set; }
        public string ChuTheViPham { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QuocTich { get; set; }
        public string NgheNghiep { get; set; }
        public string DiaChi { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string NoiDungVP { get; set; }
        public string LoiKhaiNguoiVP { get; set; }
        public string LoiKhaiNhanChung { get; set; }
        public string BienPhap { get; set; }
        public string TangVatTamGiu { get; set; }
        public string GioHen { get; set; }
        public string PhutHen { get; set; }
        public Nullable<System.DateTime> NgayHen { get; set; }
        public string DiaDiemHen { get; set; }
        public string GioXongBB { get; set; }
        public string PhutXongBB { get; set; }
        public Nullable<System.DateTime> NgayXongBB { get; set; }
        public string LyDoKhongKyBB { get; set; }
        public string NguoiLapBB { get; set; }
        public string NVNhap { get; set; }
        public Nullable<short> Sta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBienBanVPHC> CTBienBanVPHCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyetDinhTTTV> QuyetDinhTTTVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyetDinhXPVPHC> QuyetDinhXPVPHCs { get; set; }
    }
}
