//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVPHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienBanTGTV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienBanTGTV()
        {
            this.QuyetDinhTGTVs = new HashSet<QuyetDinhTGTV>();
        }
    
        public string SoBBTG { get; set; }
        public string SoQuyen { get; set; }
        public Nullable<int> GioLapBB { get; set; }
        public Nullable<int> PhutLapBB { get; set; }
        public Nullable<System.DateTime> NgayLapBB { get; set; }
        public string DiaChiLapBB { get; set; }
        public string MaNV1 { get; set; }
        public string MaNV2 { get; set; }
        public string ChuTheViPham { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QuocTich { get; set; }
        public string NgheNghiep { get; set; }
        public string DiaChi { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string NVLapBB { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NVNhap { get; set; }
        public Nullable<short> Sta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyetDinhTGTV> QuyetDinhTGTVs { get; set; }
    }
}
