//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVPHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBienBanVPHC
    {
        public int Id { get; set; }
        public string SoBBVPHC { get; set; }
        public string MaDiem { get; set; }
        public Nullable<short> Sta { get; set; }
    
        public virtual BienBanVPHC BienBanVPHC { get; set; }
    }
}
