//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVPHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public long Id { get; set; }
        public string MaDiem { get; set; }
        public Nullable<long> MaKhoan { get; set; }
        public Nullable<long> MaDieu { get; set; }
        public string MoTa { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsDetele { get; set; }
    
        public virtual Khoan Khoan { get; set; }
    }
}
