//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVPHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoQuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoQuyen()
        {
            this.QuyetDinhXPVPHCs = new HashSet<QuyetDinhXPVPHC>();
        }
    
        public string SoGiaoQuyen { get; set; }
        public Nullable<System.DateTime> NgayGiaoQuyen { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> Sta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyetDinhXPVPHC> QuyetDinhXPVPHCs { get; set; }
    }
}
