//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVPHC.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLVPHCEntities : DbContext
    {
        public QLVPHCEntities()
            : base("name=QLVPHCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BienBanTGTV> BienBanTGTVs { get; set; }
        public virtual DbSet<BienBanVPHC> BienBanVPHCs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<CTBienBanVPHC> CTBienBanVPHCs { get; set; }
        public virtual DbSet<CTQuyetDinhTTTV> CTQuyetDinhTTTVs { get; set; }
        public virtual DbSet<CTQuyetDinhXPVPHC> CTQuyetDinhXPVPHCs { get; set; }
        public virtual DbSet<Diem> Diems { get; set; }
        public virtual DbSet<Dieu> Dieux { get; set; }
        public virtual DbSet<GiaiTrinh> GiaiTrinhs { get; set; }
        public virtual DbSet<GiaoQuyen> GiaoQuyens { get; set; }
        public virtual DbSet<Khoan> Khoans { get; set; }
        public virtual DbSet<MucPhat> MucPhats { get; set; }
        public virtual DbSet<NghiDinh> NghiDinhs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<QuyetDinhTGTV> QuyetDinhTGTVs { get; set; }
        public virtual DbSet<QuyetDinhTLTV> QuyetDinhTLTVs { get; set; }
        public virtual DbSet<QuyetDinhTTTV> QuyetDinhTTTVs { get; set; }
        public virtual DbSet<QuyetDinhXPVPHC> QuyetDinhXPVPHCs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThamSo> ThamSoes { get; set; }
    }
}
