//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVPHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyetDinhTGTV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuyetDinhTGTV()
        {
            this.QuyetDinhTLTVs = new HashSet<QuyetDinhTLTV>();
        }
    
        public string SoQDTGTV { get; set; }
        public string SoBBTGTV { get; set; }
        public string SoQuyen { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayLapQD { get; set; }
        public string ChuTheVP { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QuocTich { get; set; }
        public string NgheNghiep { get; set; }
        public string DiaChi { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string TangVat { get; set; }
        public string LyDoGiaHan { get; set; }
        public Nullable<int> TGTamGiu { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string DiaDiemTG { get; set; }
        public string ChuTheTG { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NVNhap { get; set; }
        public Nullable<short> Sta { get; set; }
    
        public virtual BienBanTGTV BienBanTGTV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyetDinhTLTV> QuyetDinhTLTVs { get; set; }
    }
}
