//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVPHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyetDinhXPVPHC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuyetDinhXPVPHC()
        {
            this.CTQuyetDinhXPVPHCs = new HashSet<CTQuyetDinhXPVPHC>();
        }
    
        public string SoQD { get; set; }
        public string SoQuyen { get; set; }
        public Nullable<System.DateTime> NgapLapQD { get; set; }
        public string SoNghiDinh { get; set; }
        public string SoBBVPHC { get; set; }
        public string SoBBGiaiTrinh { get; set; }
        public string SoVBGiaoQuyen { get; set; }
        public string MaNV { get; set; }
        public string TTTangGiam { get; set; }
        public Nullable<decimal> TongTienPhat { get; set; }
        public string XuPhatBoSung { get; set; }
        public string BPNganChan { get; set; }
        public string BPKhacPhuc { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
        public Nullable<int> ThoiHanNop { get; set; }
        public string GuiDVThuTien { get; set; }
        public string GuiCho { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NVNhap { get; set; }
        public Nullable<short> Sta { get; set; }
    
        public virtual BienBanVPHC BienBanVPHC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTQuyetDinhXPVPHC> CTQuyetDinhXPVPHCs { get; set; }
        public virtual GiaiTrinh GiaiTrinh { get; set; }
        public virtual GiaoQuyen GiaoQuyen { get; set; }
        public virtual NghiDinh NghiDinh { get; set; }
    }
}
