//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVPHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyetDinhTLTV
    {
        public int Id { get; set; }
        public string SoQDTLTV { get; set; }
        public string SoQDTGTV { get; set; }
        public string SoQuyen { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayLapQD { get; set; }
        public string ChuTheViPham { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QuocTich { get; set; }
        public string NgheNghiep { get; set; }
        public string DiaChi { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string TangVat { get; set; }
        public string NVThucHien { get; set; }
        public string NVNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<short> Sta { get; set; }
    
        public virtual QuyetDinhTGTV QuyetDinhTGTV { get; set; }
    }
}
